print('{:=^25}'.format('desafio09'))
#leia um numero inteiro qualquer e realize sua tabuada
nint = int(input('digite um numero inteiro qualquer: '))
print('='*10)
print('{}x1 = {}'.format(nint, nint*1))
print('{}x2 = {}'.format(nint, nint*2))
print('{}x3 = {}'.format(nint, nint*3))
print('{}x4 = {}'.format(nint, nint*4))
print('{}x5 = {}'.format(nint, nint*5))
print('{}x6 = {}'.format(nint, nint*6))
print('{}x7 = {}'.format(nint, nint*7))
print('{}x8 = {}'.format(nint, nint*8))
print('{}x9 = {}'.format(nint, nint*9))
print('{}x10= {}'.format(nint, nint*10))
print('='*10)
